name: Generowanie_Sprawka
on: push
jobs:
  generator_pdf:
    runs-on: Ubuntu-24.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - uses: actions/checkout@v4
      - run: pip install open-atmos-jupyter-utils pint scipy nbconvert ipykernel pympdata
      - run: python -m nbconvert --to pdf --execute sdm.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: sdm.pdf
